### ISSUE TITLE
Certain emoji are not visible on windows 10

### ISSUE THREAD

**Issue by voronoipotato** [shea256/emojicoding#2]
While most of the emoji are visible in windows 10, 🧰 is not. I'm not really sure what a good strategy is for missing emoji but if you want it to be human readable I think it's important to address.

**Comment by shea256** [comment]
@voronoipotato Thanks for reporting. Can you provide more information about your Windows 10 installation? The toolbox emoji should actually show up on Windows 10. See here:

https://emojipedia.org/toolbox/

**Comment by voronoipotato** [comment]
Looks like it was added in the October 2018 update. The machine I was on was likely behind on updates. Feel free to close this.

**Comment by shea256** [comment]
OK cool, thanks for the update Alan. Closing.
